name: dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: npm install
        run:
          npm install
          # Runs a single command using the runners shell
      - name: npm build
        run: npm run build:stage

      # - uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_REPO }}
      #     tags: stage-${{ github.run_number }}

  deploy:
    name: deploy container
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    # - name: deploy to cluster
    #   uses: steebchen/kubectl@master
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #   with:
    #     args: set image --record deployment/iblogs-web iblogs=${{ secrets.DOCKER_REPO }}:stage-${{ github.run_number }} -n mybox
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist
